export const GET_COUNTRIES = "GET_COUNTRIES";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const GET_COUNTRIE_BY_NAME = "GET_COUNTRIE_BY_NAME";
export const POST_ACTIVITY = "POST_ACTIVITY";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
